vich_uploader:
    db_driver: orm

    mappings:
        avatar:
            uri_prefix: /img/avatar
            upload_destination: '%kernel.project_dir%/public/img/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        image:
            uri_prefix: /img/image
            upload_destination: '%kernel.project_dir%/public/img/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
